
/**
 *  Supported languages by Google Translate.
 */
module.exports = {
  af: /^(Afrikaans)$/i,
  sq: /^(Albanian)$/i,
  am: /^(Amharic)$/i,
  ar: /^(Arabic)$/i,
  hy: /^(Armenian)$/i,
  az: /^(Azerbaijani)$/i,
  eu: /^(Basque)$/i,
  be: /^(Belarusian)$/i,
  bn: /^(Bengali)$/i,
  bs: /^(Bosnian)$/i,
  bg: /^(Bulgarian)$/i,
  ca: /^(Catalan)$/i,
  ceb: /^(Cebuano)$/i,
  ny: /^(Chichewa)$/i,
  zh: /^(Chinese( Simplified)?)$/i,
  'zh-cn': /^(Chinese Simplified)$/i,
  'zh-tw': /^(Chinese Traditional)$/i,
  co: /^(Corsican)$/i,
  hr: /^(Croatian)$/i,
  cs: /^(Czech)$/i,
  da: /^(Danish)$/i,
  nl: /^(Dutch)$/i,
  en: /^(English)$/i,
  eo: /^(Esperanto)$/i,
  et: /^(Estonian)$/i,
  tl: /^(Filipino|Tagalog)$/i,
  fi: /^(Finnish)$/i,
  fr: /^(French)$/i,
  fy: /^(Frisian)$/i,
  gl: /^(Galician)$/i,
  ka: /^(Georgian)$/i,
  de: /^(German)$/i,
  el: /^(Greek)$/i,
  gu: /^(Gujarati)$/i,
  ht: /^(Haitian Creole)$/i,
  ha: /^(Hausa)$/i,
  haw: /^(Hawaiian)$/i,
  he: /^(Hebrew)$/i,
  iw: /^(Hebrew)$/i,
  hi: /^(Hindi)$/i,
  hmn: /^(Hmong)$/i,
  hu: /^(Hungarian)$/i,
  is: /^(Icelandic)$/i,
  ig: /^(Igbo)$/i,
  id: /^(Indonesian)$/i,
  ga: /^(Irish)$/i,
  it: /^(Italian)$/i,
  ja: /^(Japanese)$/i,
  jw: /^(Javanese)$/i,
  kn: /^(Kannada)$/i,
  kk: /^(Kazakh)$/i,
  km: /^(Khmer)$/i,
  ko: /^(Korean)$/i,
  ku: /^(Kurdish \(Kurmanji\))$/i,
  ky: /^(Kyrgyz)$/i,
  lo: /^(Lao)$/i,
  la: /^(Latin)$/i,
  lv: /^(Latvian)$/i,
  lt: /^(Lithuanian)$/i,
  lb: /^(Luxembourgish)$/i,
  mk: /^(Macedonian)$/i,
  mg: /^(Malagasy)$/i,
  ms: /^(Malay)$/i,
  ml: /^(Malayalam)$/i,
  mt: /^(Maltese)$/i,
  mi: /^(Maori)$/i,
  mr: /^(Marathi)$/i,
  mn: /^(Mongolian)$/i,
  my: /^(Myanmar \(Burmese\))$/i,
  ne: /^(Nepali)$/i,
  no: /^(Norwegian)$/i,
  ps: /^(Pashto)$/i,
  fa: /^(Persian)$/i,
  pl: /^(Polish)$/i,
  pt: /^(Portuguese)$/i,
  pa: /^(Punjabi)$/i,
  ro: /^(Romanian)$/i,
  ru: /^(Russian)$/i,
  sm: /^(Samoan)$/i,
  gd: /^(Scots Gaelic)$/i,
  sr: /^(Serbian)$/i,
  st: /^(Sesotho)$/i,
  sn: /^(Shona)$/i,
  sd: /^(Sindhi)$/i,
  si: /^(Sinhala)$/i,
  sk: /^(Slovak)$/i,
  sl: /^(Slovenian)$/i,
  so: /^(Somali)$/i,
  es: /^(Spanish)$/i,
  su: /^(Sundanese)$/i,
  sw: /^(Swahili)$/i,
  sv: /^(Swedish)$/i,
  tg: /^(Tajik)$/i,
  ta: /^(Tamil)$/i,
  te: /^(Telugu)$/i,
  th: /^(Thai)$/i,
  tr: /^(Turkish)$/i,
  uk: /^(Ukrainian)$/i,
  ur: /^(Urdu)$/i,
  uz: /^(Uzbek)$/i,
  vi: /^(Vietnamese)$/i,
  cy: /^(Welsh)$/i,
  xh: /^(Xhosa)$/i,
  yi: /^(Yiddish)$/i,
  yo: /^(Yoruba)$/i,
  zu: /^(Zulu)$/i
}
