
/**
 *  Supported languages by Google Translate.
 */
module.exports = {
  af: { name: 'Afrikaans', regex: /^(Afrikaans)$/i },
  sq: { name: 'Albanian', regex: /^(Albanian)$/i },
  am: { name: 'Amharic', regex: /^(Amharic)$/i },
  ar: { name: 'Arabic', regex: /^(Arab(ic)?)$/i },
  hy: { name: 'Armenian', regex: /^(Armenian)$/i },
  az: { name: 'Azerbaijani', regex: /^(Azerbaijani)$/i },
  eu: { name: 'Basque', regex: /^(Basque)$/i },
  be: { name: 'Belarusian', regex: /^(Belarusian)$/i },
  bn: { name: 'Bengali', regex: /^(Bengali)$/i },
  bs: { name: 'Bosnian', regex: /^(Bosnian)$/i },
  bg: { name: 'Bulgarian', regex: /^(Bulgarian)$/i },
  ca: { name: 'Catalan', regex: /^(Catalan)$/i },
  ceb: { name: 'Cebuano', regex: /^(Cebuano)$/i },
  ny: { name: 'Chichewa', regex: /^(Chichewa)$/i },
  zh: { name: 'Chinese Simplified', regex: /^(Chinese( Simplified)?)$/i },
  'zh-cn': { name: 'Chinese Simplified', regex: /^(Chinese Simplified)$/i },
  'zh-tw': { name: 'Chinese Traditional', regex: /^(Chinese Traditional)$/i },
  co: { name: 'Corsican', regex: /^(Corsican)$/i },
  hr: { name: 'Croatian', regex: /^(Croatian)$/i },
  cs: { name: 'Czech', regex: /^(Czech)$/i },
  da: { name: 'Danish', regex: /^(Danish)$/i },
  nl: { name: 'Dutch', regex: /^(Dutch)$/i },
  en: { name: 'English', regex: /^(English)$/i },
  eo: { name: 'Esperanto', regex: /^(Esperanto)$/i },
  et: { name: 'Estonian', regex: /^(Estonian)$/i },
  fi: { name: 'Finnish', regex: /^(Finnish)$/i },
  fr: { name: 'French', regex: /^(French)$/i },
  fy: { name: 'Frisian', regex: /^(Frisian)$/i },
  gl: { name: 'Galician', regex: /^(Galician)$/i },
  ka: { name: 'Georgian', regex: /^(Georgian)$/i },
  de: { name: 'German', regex: /^(German)$/i },
  el: { name: 'Greek', regex: /^(Greek)$/i },
  gu: { name: 'Gujarati', regex: /^(Gujarati)$/i },
  ht: { name: 'Haitian Creole', regex: /^(Haitian Creole)$/i },
  ha: { name: 'Hausa', regex: /^(Hausa)$/i },
  haw: { name: 'Hawaiian', regex: /^(Hawaiian)$/i },
  he: { name: 'Hebrew', regex: /^(Hebrew)$/i },
  iw: { name: 'Hebrew', regex: /^(Hebrew)$/i },
  hi: { name: 'Hindi', regex: /^(Hindi)$/i },
  hmn: { name: 'Hmong', regex: /^(Hmong)$/i },
  hu: { name: 'Hungarian', regex: /^(Hungarian)$/i },
  is: { name: 'Icelandic', regex: /^(Icelandic)$/i },
  ig: { name: 'Igbo', regex: /^(Igbo)$/i },
  id: { name: 'Indonesian', regex: /^(Indonesian)$/i },
  ga: { name: 'Irish', regex: /^(Irish)$/i },
  it: { name: 'Italian', regex: /^(Italian)$/i },
  ja: { name: 'Japanese', regex: /^(Japanese)$/i },
  jw: { name: 'Javanese', regex: /^(Javanese)$/i },
  kn: { name: 'Kannada', regex: /^(Kannada)$/i },
  kk: { name: 'Kazakh', regex: /^(Kazakh)$/i },
  km: { name: 'Khmer', regex: /^(Khmer)$/i },
  ko: { name: 'Korean', regex: /^(Korean)$/i },
  ku: { name: 'Kurdish (Kurmanji)', regex: /^(Kurdish \(Kurmanji\))$/i },
  ky: { name: 'Kyrgyz', regex: /^(Kyrgyz)$/i },
  lo: { name: 'Lao', regex: /^(Lao)$/i },
  la: { name: 'Latin', regex: /^(Latin)$/i },
  lv: { name: 'Latvian', regex: /^(Latvian)$/i },
  lt: { name: 'Lithuanian', regex: /^(Lithuanian)$/i },
  lb: { name: 'Luxembourgish', regex: /^(Luxembourgish)$/i },
  mk: { name: 'Macedonian', regex: /^(Macedonian)$/i },
  mg: { name: 'Malagasy', regex: /^(Malagasy)$/i },
  ms: { name: 'Malay', regex: /^(Malay)$/i },
  ml: { name: 'Malayalam', regex: /^(Malayalam)$/i },
  mt: { name: 'Maltese', regex: /^(Maltese)$/i },
  mi: { name: 'Maori', regex: /^(Maori)$/i },
  mr: { name: 'Marathi', regex: /^(Marathi)$/i },
  mn: { name: 'Mongolian', regex: /^(Mongolian)$/i },
  my: { name: 'Myanmar (Burmese)', regex: /^(Myanmar \(Burmese\))$/i },
  ne: { name: 'Nepali', regex: /^(Nepali)$/i },
  no: { name: 'Norwegian', regex: /^(Norwegian)$/i },
  ps: { name: 'Pashto', regex: /^(Pashto)$/i },
  fa: { name: 'Persian', regex: /^(Persian)$/i },
  pl: { name: 'Polish', regex: /^(Polish)$/i },
  pt: { name: 'Portuguese', regex: /^(Portuguese)$/i },
  pa: { name: 'Punjabi', regex: /^(Punjabi)$/i },
  ro: { name: 'Romanian', regex: /^(Romanian)$/i },
  ru: { name: 'Russian', regex: /^(Russian)$/i },
  sm: { name: 'Samoan', regex: /^(Samoan)$/i },
  gd: { name: 'Scots Gaelic', regex: /^(Scots Gaelic)$/i },
  sr: { name: 'Serbian', regex: /^(Serbian)$/i },
  st: { name: 'Sesotho', regex: /^(Sesotho)$/i },
  sn: { name: 'Shona', regex: /^(Shona)$/i },
  sd: { name: 'Sindhi', regex: /^(Sindhi)$/i },
  si: { name: 'Sinhala', regex: /^(Sinhala)$/i },
  sk: { name: 'Slovak', regex: /^(Slovak)$/i },
  sl: { name: 'Slovenian', regex: /^(Slovenian)$/i },
  so: { name: 'Somali', regex: /^(Somali)$/i },
  es: { name: 'Spanish', regex: /^(Spanish)$/i },
  su: { name: 'Sundanese', regex: /^(Sundanese)$/i },
  sw: { name: 'Swahili', regex: /^(Swahili)$/i },
  sv: { name: 'Swedish', regex: /^(Swedish)$/i },
  tl: { name: 'Tagalog', regex: /^(Filipino|Tagalog)$/i },
  tg: { name: 'Tajik', regex: /^(Tajik)$/i },
  ta: { name: 'Tamil', regex: /^(Tamil)$/i },
  te: { name: 'Telugu', regex: /^(Telugu)$/i },
  th: { name: 'Thai', regex: /^(Thai)$/i },
  tr: { name: 'Turkish', regex: /^(Turkish)$/i },
  uk: { name: 'Ukrainian', regex: /^(Ukrainian)$/i },
  ur: { name: 'Urdu', regex: /^(Urdu)$/i },
  uz: { name: 'Uzbek', regex: /^(Uzbek)$/i },
  vi: { name: 'Vietnamese', regex: /^(Vietnamese)$/i },
  cy: { name: 'Welsh', regex: /^(Welsh)$/i },
  xh: { name: 'Xhosa', regex: /^(Xhosa)$/i },
  yi: { name: 'Yiddish', regex: /^(Yiddish)$/i },
  yo: { name: 'Yoruba', regex: /^(Yoruba)$/i },
  zu: { name: 'Zulu', regex: /^(Zulu)$/i }
}
